services:
  mindsdb:
    container_name: tenanto-mindsdb
    image: mindsdb/mindsdb:latest
    restart: unless-stopped
    environment:
      - MINDSDB_APIS=http,mysql
    volumes:
      - mindsdb:/root/mdb_storage
    ports:
      - "47334:47334"
      - "47335:47335"

volumes:
  mindsdb:
